# Build and test docker image for golang application
# Setup go build environment
name: Build and test docker image for golang application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version: 1.23.3
    - name: Run go test
      run: |
        cd 1m-wk3-d2/mega-app && go test ./...
    - name: Login to Dockerhub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker image
      uses: docker/build-push-action@v6.10.0
      with:
        context: ./1m-wk3-d2/mega-app/.
        file: ./1m-wk3-d2/mega-app/Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/mega-app:latest
    # - name: Push docker image
    #   run: kubectl apply -f deployment.yaml
# Build go application
# Run go test
# Build docker image
# Push docker image to docker hub
# Deploy docker image to kubernetes cluster
